GiysiSatiyoruz/GiysiSatiyoruz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GiysiSatiyoruz.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult LayLayLom()
        {



            return View();
        }

        public ActionResult Hayvansever()
        {

            return View();
        }
        public ActionResult KALEM()
        {

            return View();


        }

        public ActionResult Defter()
        {
            return View();
        }

    }
}

GiysiSatiyoruz/GiysiSatiyoruz/Controllers/KopekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GiysiSatiyoruz.Controllers
{
    public class KopekController : Controller
    {
        // GET: Kopek
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult KopekResimler()
        {
            return View();
        }
    }
}

GiysiSatiyoruz/GiysiSatiyoruz/Controllers/kediController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GiysiSatiyoruz.Controllers
{
    public class kediController : Controller
    {
        // GET: kedi
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult kedicik()
        {
            return View();
        }
    }
}

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/Defter.cshtml
@{
    ViewBag.Title = "Defter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Defter</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/Hayvansever.cshtml
@{
    ViewBag.Title = "Hayvansever";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Hayvanseveriz öyleyse hav hav</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutTheme.cshtml";
}



<div class="col-sm-9">

    <p class="text-muted lead">In our Ladies department we offer wide selection of the best products we have found and carefully selected worldwide. Pellentesque habitant morbi tristique senectus et netuss.</p>

    <div class="row products">

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product1.jpg" )" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">Fur coat with very but very very long name</a></h3>
                    <p class="price">$143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>
                </div>
                <!-- /.text -->
            </div>
            <!-- /.product -->
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product2.jpg" )" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">White Blouse Armani</a></h3>
                    <p class="price"><del>$280</del> $143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>
                </div>
                <!-- /.text -->

                <div class="ribbon sale">
                    <div class="theribbon">SALE</div>
                    <div class="ribbon-background"></div>
                </div>
                <!-- /.ribbon -->

                <div class="ribbon new">
                    <div class="theribbon">NEW</div>
                    <div class="ribbon-background"></div>
                </div>
                <!-- /.ribbon -->
            </div>
            <!-- /.product -->
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product3.jpg" )" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">Black Blouse Versace</a></h3>
                    <p class="price">$143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>

                </div>
                <!-- /.text -->
            </div>
            <!-- /.product -->
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product3.jpg" )" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">Black Blouse Versace</a></h3>
                    <p class="price">$143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>

                </div>
                <!-- /.text -->
            </div>
            <!-- /.product -->
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product2.jpg")" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">White Blouse Versace</a></h3>
                    <p class="price">$143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>

                </div>
                <!-- /.text -->

                <div class="ribbon new">
                    <div class="theribbon">NEW</div>
                    <div class="ribbon-background"></div>
                </div>
                <!-- /.ribbon -->
            </div>
            <!-- /.product -->
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="image">
                    <a href="shop-detail.html">
                        <img src="@Url.Content("~/Image/product1.jpg" )" alt="" class="img-responsive image1">
                    </a>
                </div>
                <!-- /.image -->
                <div class="text">
                    <h3><a href="shop-detail.html">Fur coat</a></h3>
                    <p class="price">$143.00</p>
                    <p class="buttons">
                        <a href="shop-detail.html" class="btn btn-default">View detail</a>
                        <a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </p>

                </div>
                <!-- /.text -->
            </div>
            <!-- /.product -->
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.products -->

    <div class="row">

        <div class="col-md-12 banner">
            <a href="#">
                <img src="@Url.Content("~/Image/banner2.jpg")" alt="" class="img-responsive">
            </a>
        </div>

    </div>


    <div class="pages">

        <p class="loadMore">
            <a href="#" class="btn btn-template-main"><i class="fa fa-chevron-down"></i> Load more</a>
        </p>

        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>


</div>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/KALEM.cshtml
@{
    ViewBag.Title = "KALEM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>KALEM</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Home/LayLayLom.cshtml
@{
    ViewBag.Title = "LayLayLom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LayLayLom Galiba sana göre sevmeler</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Kopek/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index- Ben kopekleri cok sviyorum</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Kopek/KopekResimler.cshtml
@{
    ViewBag.Title = "KopekResimler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>KopekResimler</h2>
<h2>Karabas</h2>
<h2>coni</h2>
<h2>lara</h2>
<h2>raf</h2>

GiysiSatiyoruz/GiysiSatiyoruz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Esek</a>
                        <ul class="dropdown-menu">

                            <li>@Html.ActionLink("LayLay", "LayLayLom", "Home")</li>
                            <li>@Html.ActionLink("Hav", "Hayvansever", "Home")</li>
                            <li>@Html.ActionLink("REYHAN", "KALEM", "Home")</li>
                            <li>@Html.ActionLink("Ruya", "Defter", "Home")</li> 
                        </ul>
                    </li>

                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kedi</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Kedi", "kedicik", "kedi")</li>
                            <li>@Html.ActionLink("Kedi", "Index", "kedi")</li>
                        </ul>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kopek</a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Kopekler", "KopekResimler", "Kopek")</li>
                                    <li>@Html.ActionLink("Kopekler2", "Index", "Kopek")</li>
                                </ul>
                            </li>
                        </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GiysiSatiyoruz/GiysiSatiyoruz/Views/kedi/kedicik.cshtml
@{
    ViewBag.Title = "kedicik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>kedicik</h2>